.loc[] can access: ROWS,COLUMNS, BOTH ROWS AND COLUMNS \n
// TO ACCESS COLUMNS:\n
df.loc[0:1,"name"]
for cols -> []
for rows -- > iloc [same like indexing]

| Code                        | Output Type |
| --------------------------- | ----------- |
| `d1.loc['ROW1']`            | Series      |
| `d1.loc[['ROW1']]`          | DataFrame   |
| `d1['col1']`                | Series      |
| `d1[['col1']]`              | DataFrame   |
| `d1.loc['ROW1','col1']`     | Scalar      |
| `d1.loc[['ROW1'],['col1']]` | DataFrame   |
Rule:
Selecting a single row or single column → returns a Series
Selecting multiple rows or multiple columns → returns a DataFrame

In [2]:
import numpy as np

In [3]:
import pandas as pd

**#creation of dataframes**

In [4]:
d1 = pd.DataFrame(np.arange(0,20).reshape(4,5),index=['ROW1','ROW2','ROW3','ROW4'],columns=['col1','col2','col3','col4','col5'])

In [5]:
d1.head()

      col1  col2  col3  col4  col5
ROW1     0     1     2     3     4
ROW2     5     6     7     8     9
ROW3    10    11    12    13    14
ROW4    15    16    17    18    19

In [15]:
d1.values

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
d1.value_counts()

col1  col2  col3  col4  col5
0     1     2     3     4       1
5     6     7     8     9       1
10    11    12    13    14      1
15    16    17    18    19      1
Name: count, dtype: int64

In [14]:
d1.loc[['ROW1']].values

array([[0, 1, 2, 3, 4]])

In [12]:
d1.loc[['ROW1']].value_counts()

col1  col2  col3  col4  col5
0     1     2     3     4       1
Name: count, dtype: int64

In [17]:
d1.iloc[0:2,0:4:].value_counts()

col1  col2  col3  col4
0     1     2     3       1
5     6     7     8       1
Name: count, dtype: int64

In [7]:
d1.loc[['ROW1','ROW2'],['col1','col2']]

      col1  col2
ROW1     0     1
ROW2     5     6

In [7]:
d1.loc[['ROW1','ROW2']]

      col1  col2  col3  col4  col5
ROW1     0     1     2     3     4
ROW2     5     6     7     8     9

In [8]:
type(d1.loc[['ROW1','ROW2']])

pandas.core.frame.DataFrame

In [9]:
type(d1.loc['ROW1'])

pandas.core.series.Series

In [10]:
d1.loc[['ROW1']]

      col1  col2  col3  col4  col5
ROW1     0     1     2     3     4

In [11]:
type(d1.loc[['ROW1']])

pandas.core.frame.DataFrame

In [12]:
d1.loc['ROW1']

col1    0
col2    1
col3    2
col4    3
col5    4
Name: ROW1, dtype: int64

In [13]:
type(d1.loc['ROW1'])

pandas.core.series.Series

In [14]:
d2 = pd.DataFrame(np.arange(0,20).reshape(4,5),index=['ROW1','ROW2','ROW3','ROW4'],columns=['col1','col2','col3','col4','col5'])

In [15]:
d2

      col1  col2  col3  col4  col5
ROW1     0     1     2     3     4
ROW2     5     6     7     8     9
ROW3    10    11    12    13    14
ROW4    15    16    17    18    19

In [16]:
#use of iloc--> same like numpy indexing
d2.iloc[:,:]

      col1  col2  col3  col4  col5
ROW1     0     1     2     3     4
ROW2     5     6     7     8     9
ROW3    10    11    12    13    14
ROW4    15    16    17    18    19

In [17]:
d2.iloc[0:,0:].values

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
type(d2.iloc[0:3,0:3])

pandas.core.frame.DataFrame

In [19]:
d2.iloc[0:,0]

ROW1     0
ROW2     5
ROW3    10
ROW4    15
Name: col1, dtype: int64

In [20]:
type(d2.iloc[0:,0])

pandas.core.series.Series

In [21]:
d2.iloc[0:2,0:1]

      col1
ROW1     0
ROW2     5

data frames to arrays

In [22]:
d2.iloc[0:,0].values

array([ 0,  5, 10, 15])

In [23]:
d2.isnull().sum() # to check whether NAN OR NULL VALUES PRESENT

col1    0
col2    0
col3    0
col4    0
col5    0
dtype: int64

In [24]:
d2['col1'].value_counts()

col1
0     1
5     1
10    1
15    1
Name: count, dtype: int64

In [25]:
d2['col1'].unique()

array([ 0,  5, 10, 15])

In [26]:
d2.loc[:,"col1"]

ROW1     0
ROW2     5
ROW3    10
ROW4    15
Name: col1, dtype: int64

In [27]:
d2.loc[['ROW1','ROW2'],'col1']

ROW1    0
ROW2    5
Name: col1, dtype: int64

In [28]:
d3 = pd.DataFrame(np.arange(0,20).reshape(5,4),index = ['ROW1','ROW2','ROW3','ROW4','ROW5'],columns = ['col1','col2','col3','col4'])

In [29]:
d3

      col1  col2  col3  col4
ROW1     0     1     2     3
ROW2     4     5     6     7
ROW3     8     9    10    11
ROW4    12    13    14    15
ROW5    16    17    18    19

In [30]:
d3.loc['ROW1']

col1    0
col2    1
col3    2
col4    3
Name: ROW1, dtype: int64

In [31]:
d3.loc[['ROW1','ROW2'],'col1']

ROW1    0
ROW2    4
Name: col1, dtype: int64

In [32]:
d3.loc[:,'col1']

ROW1     0
ROW2     4
ROW3     8
ROW4    12
ROW5    16
Name: col1, dtype: int64

In [33]:
d3.iloc[0:2,0:2]

      col1  col2
ROW1     0     1
ROW2     4     5

In [34]:
d3.iloc[0:2,0:2].values

array([[0, 1],
       [4, 5]])

In [35]:
d3.iloc[0:2,0:2].value_counts()

col1  col2
0     1       1
4     5       1
Name: count, dtype: int64