In [4]:
import numpy as np

In [2]:
list1 = [1,2,3]
array1 = np.array(list1)

In [3]:
array1

array([1, 2, 3])

In [5]:
array1.size

3

In [10]:
list2 = [4,5,6]
list3 = [7,8,9]
array5 = np.array([list1,list2,list3])

In [11]:
array5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
array5.resize(1,9)

In [15]:
array5

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [1]:
#dataframe

In [9]:
import pandas as pd

In [10]:
d1 = pd.DataFrame(np.arange(0,20).reshape(4,5),index = ['r1','r2','r3','r4'],columns=['c1','c2','c3','c4','c5'])

In [11]:
d1

    c1  c2  c3  c4  c5
r1   0   1   2   3   4
r2   5   6   7   8   9
r3  10  11  12  13  14
r4  15  16  17  18  19

In [15]:
d1.loc[['r1','r2']]

    c1  c2  c3  c4  c5
r1   0   1   2   3   4
r2   5   6   7   8   9

In [16]:
d1.iloc[0:4,0:3]

    c1  c2  c3
r1   0   1   2
r2   5   6   7
r3  10  11  12
r4  15  16  17

In [18]:
d1.iloc[0:4,0:3].values

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]])

In [20]:
d1.iloc[0:4,0:1].value_counts()

c1
0     1
5     1
10    1
15    1
Name: count, dtype: int64

In [21]:
d4 = pd.DataFrame(np.arange(0,20).reshape(4,5),index = ['r1','r2','r3','r4'],columns=['c1','c2','c3','c4','c5'])

In [23]:
d4

    c1  c2  c3  c4  c5
r1   0   1   2   3   4
r2   5   6   7   8   9
r3  10  11  12  13  14
r4  15  16  17  18  19

In [24]:
d4.loc['r1']

c1    0
c2    1
c3    2
c4    3
c5    4
Name: r1, dtype: int64

In [25]:
d4.loc[['r1','r2'],'c1']

r1    0
r2    5
Name: c1, dtype: int64

In [26]:
d4.iloc[:,:]

    c1  c2  c3  c4  c5
r1   0   1   2   3   4
r2   5   6   7   8   9
r3  10  11  12  13  14
r4  15  16  17  18  19

In [33]:
d4['c1'].unique()

array([ 0,  5, 10, 15])

In [37]:
d4.loc[['r1','r2'],'c1']

r1    0
r2    5
Name: c1, dtype: int64

In [35]:
d4.iloc[0:3,]

    c1  c2  c3  c4  c5
r1   0   1   2   3   4
r2   5   6   7   8   9
r3  10  11  12  13  14

In [38]:
d4.loc['r1']

c1    0
c2    1
c3    2
c4    3
c5    4
Name: r1, dtype: int64

In [39]:
d4.loc[['r1']]

    c1  c2  c3  c4  c5
r1   0   1   2   3   4